spring: 
  application:
    name: zuul-server
    
server:   port: 8080
    
zuul:   routes:
    booking:
      service-id: booking
      path: /bookings/**
    room:
      service-id: room
      path: /rooms/**    users:
      service-id: user
      path: /users/**